MvcOnlineTicariOtomasyon/Controllers/GrafikController.cs
using MvcOnlineTicariOtomasyon.Models.Context;
using MvcOnlineTicariOtomasyon.Models.Entities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class GrafikController : Controller
    {
        MvcTicariOtomasyonContext _context=new MvcTicariOtomasyonContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index2()
        {
            var grafikciz = new Chart(600,600);
            grafikciz.AddTitle("Kategoriler ve Ürün Sayıları").AddLegend("Stok")
                .AddSeries("Degerler", xValue: new[] { "Mobilya", "Ofis Eşyaları", "Koltuk" }, yValues: new[] { 500, 300, 750 }).Write();
            return File(grafikciz.ToWebImage().GetBytes(), "image/jpeg");
        }
        public ActionResult Index3()
        {
            ArrayList xvalue=new ArrayList();  
            ArrayList yvalue=new ArrayList();  
            var sonuclar=_context.Products.ToList();
            sonuclar.ToList().ForEach(x=>xvalue.Add(x.ProductName));
            sonuclar.ToList().ForEach(y=>yvalue.Add(y.Stock));
            var grafik=new Chart(600,600);
            grafik.AddTitle("Stoklar")
                .AddSeries(chartType: "Pie", name: "Stok", xValue: xvalue, yValues: yvalue);
            return File(grafik.ToWebImage().GetBytes(), "image/jpeg");
        }
        public ActionResult Index4()
        {

            return View();
        }
        public ActionResult VisulazieProductResult()
        {
            return Json(Productlist(), JsonRequestBehavior.AllowGet);
        }

        public List<sinif1> Productlist()
        {
            List<sinif1> snf=new List<sinif1>();
            snf.Add(new sinif1()
            {
                ProductName = "Bilgisayar",
                Stock=120,
            });
            snf.Add(new sinif1()
            {
                ProductName = "Telefon",
                Stock = 150,
            });
            snf.Add(new sinif1()
            {
                ProductName = "Beyaz Eşya",
                Stock = 400,
            });
            snf.Add(new sinif1()
            {
                ProductName = "Mobilya",
                Stock = 250,
            });
            snf.Add(new sinif1()
            {
                ProductName = "Küçük Ev Aletleri",
                Stock = 160,
            });
            return snf;
        }

        public ActionResult Index5()
        {

            return View();
        }
        public ActionResult VisulazieProductResult2()
        {
            return Json(Urunlistesi(), JsonRequestBehavior.AllowGet);
        }
        public List<sinif2> Urunlistesi()
        {
            List<sinif2> snf = new List<sinif2>();

            using (var c=new MvcTicariOtomasyonContext())
            {
                snf = c.Products.Select(x => new sinif2
                {
                    ProductName = x.ProductName,
                     Stock=x.Stock,
                }).ToList();
            }
            return snf;     
        }
        public ActionResult Index6()
        {

            return View();
        }
        public ActionResult VisulazieProductResult3()
        {
            return Json(Urunlistesi2(), JsonRequestBehavior.AllowGet);
        }
        public List<sinif2> Urunlistesi2()
        {
            List<sinif2> snf = new List<sinif2>();

            using (var c = new MvcTicariOtomasyonContext())
            {
                snf = c.Products.Select(x => new sinif2
                {
                    ProductName = x.ProductName,
                    Stock = x.Stock,
                }).ToList();
            }
            return snf;
        }
        public ActionResult Index7()
        {

            return View();
        }
        public ActionResult VisulazieProductResult4()
        {
            return Json(Urunlistesi3(), JsonRequestBehavior.AllowGet);
        }
        public List<sinif2> Urunlistesi3()
        {
            List<sinif2> snf = new List<sinif2>();

            using (var c = new MvcTicariOtomasyonContext())
            {
                snf = c.Products.Select(x => new sinif2
                {
                    ProductName = x.ProductName,
                    Stock = x.Stock,
                }).ToList();
            }
            return snf;
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Grafik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

@{ 
    var grafik = new Chart(width: 500, height: 500);
    grafik.AddTitle(text:"Kategoriler ve Ürün Sayıları");
    grafik.AddLegend(title: "Degerler");
    grafik.AddSeries(
        name: "Veriler",
        chartType: "Doughnut",
        xValue: new[] { "Beyaz Eşya", "Televizyon", "Bilgisayar", "Küçük Ev Aletleri" },
        yValues:new[] {500,250,340,650}
        );
    grafik.Write();
}

MvcOnlineTicariOtomasyon/Views/Grafik/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index2</h2>

<div style="width:600px;height:600px">
    <img src="@Url.Action("Index2","Grafik")"/>
</div>

MvcOnlineTicariOtomasyon/Views/Grafik/Index3.cshtml
@{
    ViewBag.Title = "Index3";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index3</h2>
<img  src="@Url.Action("Index3","Grafik")"/>

MvcOnlineTicariOtomasyon/Views/Grafik/Index4.cshtml
@{
    ViewBag.Title = "Index4";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h1>Ürün - Stok Grafiği</h1>
<html lang="en">

<head>

    <title>Result Visualization</title>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisulazieProductResult", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stoklar');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.ProductName, obj.Stock]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

 /*               title: "Ürün-Stok Grafiği",*/

                width: 1200,

                height: 800,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.PieChart(document

                .getElementById('piechart_div'));
            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="piechart_div"></div>

 

</body>

</html>

MvcOnlineTicariOtomasyon/Views/Grafik/Index5.cshtml
@{
    ViewBag.Title = "Index5";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h1>Ürün - Stok Grafiği</h1>
<html lang="en">

<head>

    <title>Result Visualization</title>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisulazieProductResult2", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stoklar');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.ProductName, obj.Stock]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

             /*   title: "Ürün-Stok Grafiği",*/

                width: 1200,

                height: 800,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.PieChart(document

                .getElementById('piechart_div'));
            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="piechart_div"></div>



</body>

</html>

MvcOnlineTicariOtomasyon/Views/Grafik/Index6.cshtml
@{
    ViewBag.Title = "Index6";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h1>Ürün - Stok Grafiği</h1>
<html lang="en">

<head>

    <title>Result Visualization</title>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisulazieProductResult3", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stoklar');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.ProductName, obj.Stock]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

             /*   title: "Ürün-Stok Grafiği",*/

                width: 1200,

                height: 600,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.LineChart(document

                .getElementById('linechart_div'));
            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="linechart_div"></div>



</body>

</html>

MvcOnlineTicariOtomasyon/Views/Grafik/Index7.cshtml
@{
    ViewBag.Title = "Index7";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h1>Ürün - Stok Grafiği</h1>
<html lang="en">

<head>

    <title>Result Visualization</title>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {

            $.ajax({

                type: "POST",

                dataType: "json",

                contentType: "application/json",

                url: '@Url.Action("VisulazieProductResult4", "Grafik")',

                success: function (result) {

                    google.charts.load('current', {

                        'packages': ['corechart']

                    });

                    google.charts.setOnLoadCallback(function () {

                        drawChart(result);

                    });

                }

            });

        });



        function drawChart(result) {

            var data = new google.visualization.DataTable();

            data.addColumn('string', 'Name');

            data.addColumn('number', 'Stoklar');

            var dataArray = [];



            $.each(result, function (i, obj) {

                dataArray.push([obj.ProductName, obj.Stock]);

            });

            data.addRows(dataArray);



            var columnChartOptions = {

             /*   title: "Ürün-Stok Grafiği",*/

                width: 1200,

                height: 600,

                bar: { groupWidth: "20%" },

            };



            var columnChart = new google.visualization.ColumnChart(document

                .getElementById('columnchart_div'));
            columnChart.draw(data, columnChartOptions);

        }

    </script>

</head>

<body>

    <div id="columnchart_div"></div>



</body>

</html>