MvcOnlineTicariOtomasyon/Controllers/StatisticController.cs
using MvcOnlineTicariOtomasyon.Models.Context;
using MvcOnlineTicariOtomasyon.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class StatisticController : Controller
    {
        // GET: Statistic
        MvcTicariOtomasyonContext _context = new MvcTicariOtomasyonContext();
        public ActionResult Index()
        {
            var deger1 = _context.Carilers.Count().ToString();
            ViewBag.d1 = deger1;
            var deger2 = _context.Products.Count().ToString();
            ViewBag.d2 = deger2;
            var deger3= _context.Employees.Count().ToString();
            ViewBag.d3=deger3;
            var deger4=_context.Categories.Count().ToString();
            ViewBag.d4 = deger4;
            var deger5=_context.Products.Select(x=>(int)x.Stock).Sum().ToString();
            ViewBag.d5 = deger5;
            var deger6 = _context.Products.GroupBy(x => x.Brand).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.d6 = deger6;
            var deger7=_context.Products.Where(x=>x.Stock<=20).Count().ToString();
            ViewBag.d7 = deger7;
            var deger8=(from x in _context.Products orderby x.SalePrice descending select x.ProductName).FirstOrDefault();
            ViewBag.d8 = deger8;
            var deger9 = (from x in _context.Products orderby x.SalePrice ascending select x.ProductName).FirstOrDefault();
            ViewBag.d9 = deger9;
            var deger10 = _context.Products.Select(x=>x.Brand).Distinct().Count().ToString();
            ViewBag.d10 = deger10;
            var deger11 = _context.Products.Count(x => x.CategoryID == 1).ToString();
            ViewBag.d11 = deger11;
            var deger12 = _context.Products.Count(x => x.CategoryID == 7).ToString();
            ViewBag.d12 = deger12;
            var deger13 = _context.Products.Where(u => u.ProductID ==
            (_context.SatisHarekets.GroupBy(x => x.ProductID).OrderByDescending(z => z.Count()).Select(x => x.Key).FirstOrDefault())).Select(k => k.ProductName).FirstOrDefault();
            ViewBag.d13 = deger13;
            var deger14 = _context.SatisHarekets.Sum(x => x.ToplamTutar).ToString();
            ViewBag.d14 = deger14;
            DateTime bugün = DateTime.Today;
            var deger15 = _context.SatisHarekets.Count(x => x.Tarih== bugün).ToString();
            ViewBag.d15 = deger15;
            var deger16 = _context.SatisHarekets.Where(x => x.Tarih == bugün).Sum(x => (decimal?)x.ToplamTutar) ?? 0;
            ViewBag.d16 = deger16;

            //var deger16 = _context.SatisHarekets.Where(x => x.Tarih == bugün).Sum(x => x.ToplamTutar).ToString();
            //ViewBag.d16 = deger16;

            return View();
        }
        public ActionResult SimpleTables()
        {
            var sorgu = from x in _context.Carilers
                           group x by x.CariSehir into g
                           select new EntitesGroup
                           {
                               Sehir = g.Key,
                               Sayı = g.Count()
                           };
            return View(sorgu.ToList());
        }
        public PartialViewResult Partial1()
        {
            var sorgu = from x in _context.Employees
                        group x by new { x.DepartmentID, x.Department.DepartmentName } into g
                        select new EntitesGroup2
                        {
                            DepartmanName = g.Key.DepartmentName, // buraya map ediyoruz
                            Sayi = g.Count()
                        };
            return PartialView(sorgu.ToList());
        }
        public PartialViewResult Partial2()
        {
            var sorgu = _context.Carilers.ToList();
            return PartialView(sorgu);
        }
        public PartialViewResult Partial3()
        {
            var sorgu = _context.Products.ToList();
            return PartialView(sorgu);
        }
        public PartialViewResult Partial4()
        {
            var sorgu = from x in _context.Products
                        group x by x.Brand into g
                        select new EntitiesGroup3
                        {
                            Brand = g.Key,
                            Sayi = g.Count()
                        };
            return PartialView(sorgu.ToList());
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Statistic/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="js/zingchart.min.js"></script>
    <script src="js/zingchart.jquery.js"></script>
    <script src="js/jquery.easydropdown.js"></script>
    <script src="js/jquery.nicescroll.js"></script>

    <link href="css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Toplam Cari</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Ürün Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Personel Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Kategori Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Toplam Stok</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Marka Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Kritik Seviye</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3 style="font-size:30px">@ViewBag.d8</h3>
                    <p>Max Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3 style="font-size:35px">@ViewBag.d9</h3>
                    <p>Min Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.d10</h3>
                    <p>Max Marka</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.d11</h3>
                    <p>Buzdolabı Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Laptop Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3 style="font-size:35px">@ViewBag.d13</h3>
                    <p>En Çok Satan</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.d14</h3>
                    <p>Kasadaki Tutar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.d15</h3>
                    <p>Bugünkü Satşlar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.d16</h3>
                    <p>Bugünkü Kasa</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

MvcOnlineTicariOtomasyon/Views/Statistic/Partial1.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.Entities.EntitesGroup2>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayı</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Progress</th>
                    <th style="width: 40px">Sayi</th>
                </tr>
            </thead>
            <tbody>
                @{
                int count=0;
                }
                @foreach (var item in Model)
                {
                    count++;
                    <tr>
                        <td>@count)</td>
                        <td>@item.DepartmanName</td>
                        <td>
                            @if (item.Sayi == 1)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-danger" style="width:@(10*item.Sayi)%"></div>
                                </div>
                            }
                            @if (item.Sayi == 2)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width:@(10*item.Sayi)%"></div>
                                </div>
                            }
                            @if (item.Sayi == 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-info" style="width:@(10*item.Sayi)%"></div>
                                </div>
                            }
                        </td>

                        @if (item.Sayi == 1)
                        {
                            <td><span class="badge bg-gradient-danger">@item.Sayi Kişi</span></td>
                        }
                        @if (item.Sayi == 2)
                        {
                            <td><span class="badge bg-gradient-warning">@item.Sayi Kişi</span></td>
                        }
                        @if (item.Sayi == 3)
                        {
                            <td><span class="badge bg-gradient-info">@item.Sayi Kişi</span></td>
                        }
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

MvcOnlineTicariOtomasyon/Views/Statistic/Partial2.cshtml
@model List<MvcOnlineTicariOtomasyon.Models.Entities.Cariler>
<div class="card-header">
    <h3 class="card-title">Cari Hover Tablosu</h3>

    <div class="card-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </div>
</div>
<!-- /.card-header -->
<div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th>#</th>
                <th>Cari Ad</th>
                <th>Cari Soyad</th>
                <th>Cari Mail</th>
                <th>Şehir</th>
        
            </tr>
        </thead>
        <tbody>
            @{ 
                int count = 0;
            }

            @foreach (var item in Model)
            {
                count++;
                <tr>
                   
                    <td>@count</td>
                    <td>@item.CariName</td>
                    <td>@item.CariSurname</td>
                    <td>@item.CariMail</td>
                    <td>@item.CariSehir</td>
                
                   
                </tr>
            }

        </tbody>
    </table>
</div>
<!-- /.card-body -->

MvcOnlineTicariOtomasyon/Views/Statistic/Partial3.cshtml
@model List<MvcOnlineTicariOtomasyon.Models.Entities.Product>

<div class="card-header">
    <h3 class="card-title">Ürünler Hover Tablosu</h3>

    <div class="card-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </div>
</div>
<!-- /.card-header -->
<div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th>#</th>
                <th>Ürün Resmi</th>
                <th>Ürün Adı</th>
                <th>Marka</th>
                <th>Stok</th>
                <th>Alış Fiyatı</th>
                <th>Satış Fiyatı</th>
               

            </tr>
        </thead>
        <tbody>
            @{
                int count = 0;
            }

            @foreach (var item in Model)
            {
                count++;
                <tr>

                    <td>@count</td>
                    <td><img  src="@item.ProductImage" style="width:50px"/></td>
                    <td>@item.ProductName</td>
                    <td>@item.Brand</td>
                    <td>@item.Stock</td>
                    <td>@item.PurchasePrice ₺</td>
                    <td>@item.SalePrice ₺</td>
                </tr>
            }

        </tbody>
    </table>
</div>
<!-- /.card-body -->

MvcOnlineTicariOtomasyon/Views/Statistic/SimpleTables.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.Entities.EntitesGroup>
@{
    ViewBag.Title = "SimpleTables";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int count = 0;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">



        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <br />
                        <h1>Basit Tablolar </h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Simple Tables</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Kategori Tablosu</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Kategori Adı:</th>
                                            <th>Progress Bar</th>
                                            <th style="width: 40px">Oran</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1.</td>
                                            <td>Beyaz Eşya</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-danger">55%</span></td>
                                        </tr>
                                        <tr>
                                            <td>2.</td>
                                            <td>Telefon</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-warning">70%</span></td>
                                        </tr>
                                        <tr>
                                            <td>3.</td>
                                            <td>Bilgisayar</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-primary">30%</span></td>
                                        </tr>
                                        <tr>
                                            <td>4.</td>
                                            <td>Televizyon</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-success">90%</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
              
                        </div>
                        <!-- /.card -->
                        @Html.Action("Partial1", "Statistic")
                        
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Müşteri Şehir Tablosu</h3>

                                <div class="card-tools">
                                
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Şehir</th>
                                            <th>Progress Bar</th>
                                            <th style="width: 40px">Adet</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            count++;
                                            <tr>
                                                <td>@count)</td>
                                                <td>@item.Sehir</td>
                                                <td>
                                                    @if (item.Sayı == 1)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-danger" style="width:@(10*item.Sayı)%"></div>
                                                        </div>
                                                    }
                                                    @if (item.Sayı == 2)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-warning" style="width:@(10*item.Sayı)%"></div>
                                                        </div>
                                                    }
                                                    @if (item.Sayı == 3)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-info" style="width:@(10*item.Sayı)%"></div>
                                                        </div>
                                                    }
                                                </td>
                                              
                                                    @if (item.Sayı == 1)
                                                    {
                                                      <td><span class="badge bg-gradient-danger">@item.Sayı Kişi</span></td>
                                                    }
                                                    @if (item.Sayı == 2)
                                                    {
                                                        <td><span class="badge bg-gradient-warning">@item.Sayı Kişi</span></td>
                                                    }
                                                    @if (item.Sayı == 3)
                                                    {
                                                        <td><span class="badge bg-gradient-info">@item.Sayı Kişi</span></td>
                                                    }
                                                   

                                                </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                        <div class="card">
                            @Html.Action("Partial4", "Statistic")
                           
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @Html.Action("Partial2","Statistic")
                            
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @Html.Action("Partial3", "Statistic")
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
        <!-- /.content-wrapper -->
     

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>