MvcOnlineTicariOtomasyon/Controllers/QRController.cs
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class QRController : Controller
    {
        // GET: QR
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string code)
        {
            using (MemoryStream ms=new MemoryStream())
            {
                QRCodeGenerator koduret = new QRCodeGenerator();
                QRCodeGenerator.QRCode karekod = koduret.CreateQrCode(code,QRCodeGenerator.ECCLevel.Q);
                using (Bitmap resim = karekod.GetGraphic(10))
                {
                    resim.Save(ms, ImageFormat.Png);
                    ViewBag.kareKodImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();
        }
    }
}

MvcOnlineTicariOtomasyon/Views/QR/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<div>
    @using (Html.BeginForm("Index", "QR", FormMethod.Post)) { 
        <input type="text" name="code"/>
        <input type="submit" value="QR Oluştur"/>
    }
    <br />
     @if (ViewBag.kareKodImage != null)
            {
                <img src="@ViewBag.kareKodImage" style="width:400px;height:400px"/>
            }
</div>