MvcOnlineTicariOtomasyon/Models/Entities/KargoTakip.cs
using Microsoft.CodeAnalysis.Options;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Entities
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipID { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(20)]
        public string TakipKodu { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Aciklama { get; set; }
        public DateTime TarihZaman{ get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using MvcOnlineTicariOtomasyon.Models.Context;
using MvcOnlineTicariOtomasyon.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo

        MvcTicariOtomasyonContext _context=new MvcTicariOtomasyonContext();
        public ActionResult Index(string p)
        {
            var kargo = from x in _context.KargoDetays select x;
            if (!string.IsNullOrEmpty(p))
            {
                kargo = kargo.Where(y => y.TakipKodu.Contains(p));
               
            }
            return View(kargo.ToList());
        }
        [HttpGet]
        public ActionResult CreateKargo()
        {
            Random rnd = new Random();
            string[] karakterler = { "A", "B", "C", "D", "E", "F", "G", "H","K"};
            int k1, k2, k3;
            k1=rnd.Next(0, karakterler.Length-1);
            k2=rnd.Next(0, karakterler.Length - 1);
            k3=rnd.Next(0, karakterler.Length - 1);
            int s1,s2,s3;
            s1=rnd.Next(100,1000);//10 
            s2=rnd.Next(10,99);
            s3=rnd.Next(10,99);
            string kod = s1.ToString() + karakterler[k1] + s2 + karakterler[k2] + s3 + karakterler[k3];
            ViewBag.TakipKod = kod;


            List<SelectListItem> deger3 = (from x in _context.Employees.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.EmployeeName + " " + x.EmployeeSurname,
                                               Value = x.EmployeeID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult CreateKargo(KargoDetay k)
        {
           
            _context.KargoDetays.Add(k);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KargoTakip(string id)
        {
            var degerler = _context.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/CreateKargo.cshtml
@using MvcOnlineTicariOtomasyon.Models.Entities
@model KargoDetay
@{
    ViewBag.Title = "CreateKargo";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<div style="margin:10px 20px">
    <h2>Yeni Kargo Sayfası</h2>
    <br />
    <form class="form-group" method="post">
        <label for="takipkodu">Takip Kodu</label>
        <input type="text" value="@ViewBag.TakipKod" readonly class="form-control" name="takipkodu"/>
        <br />

        <label for="Personel">Personel</label>
        @Html.TextBoxFor(m => m.Personel, new { @class = "form-control" })
        <br />
        <label for="Alıcı">Alıcı</label>
        @Html.TextBoxFor(m => m.Alici, new { @class = "form-control" })
        <br />
        <label for="Tarih">Tarih</label>
        <input type="date" name="Tarih" class="form-control" />
        <br />
        <label for="Acıklama">Açıklama</label>
        @Html.TextAreaFor(m => m.Aciklama, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </form>
</div>

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@model List<MvcOnlineTicariOtomasyon.Models.Entities.KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int count = 0;
}
<div style="margin:10px 20px ">
    @using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
    {
        <p>
            Kargo Takip Numarası: @Html.TextBox("p")
            <input type="submit" value="Ara" />
        </p>
    }
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Personel</th>
                <th scope="col">Takip Kodu</th>
                <th scope="col">Alıcı</th>
                <th scope="col">Tarih</th>
                <th scope="col">Detaylar</th>


            </tr>
        </thead>
        <tbody>
            @if (!Model.Any())
            {
                <tr>
                    <td colspan="12" class="text-center">Hiç Kargo Detayı bulunamadı.</td>
                </tr>
            }
            else
            {
                foreach (var item in Model)
                {
                    count++;
                    <tr>
                        <td scope="row">@count</td>
                        <td>@item.Personel</td>
                        <td>@item.TakipKodu</td>
                        <td>@item.Alici</td>
                        <td>@item.Tarih.ToShortDateString()</td>
                        <td><a class="btn btn-group" style="background-color:plum" href="/Kargo/KargoTakip/@item.TakipKodu">Detaylar</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <br />
    <a class="btn btn-primary" href="/Kargo/CreateKargo">Kargo Detay Ekle</a>
</div>

<script>
    setTimeout(function () {
        var message = document.getElementById("tempMessage");
        if (message) {
            message.style.display = "none";
        }
    }, 5000); // 5 saniye

    var statusButtons = document.getElementById("status");

</script>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Entities
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int count = 0;
}

<br />
<div style="margin:10px 20px">
    <h2>Kargo Detay</h2>
    <br />
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Kargo Takip Kodu</th>
                <th scope="col">Açıklama</th>
                <th scope="col">Tarih</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td scope="row">@count</td>
                    <td>@item.TakipKodu</td>
                    <td>@item.Aciklama</td>
                    <td>@item.TarihZaman.ToShortDateString()</td>
                    @*<td><a class="btn btn-danger" href="/Departman/DepartmanPersonelSatis/@item.KargoTakipID">Satışlar</a></td>*@
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-info" href="/Departman/Index">Geri Dön</a>
</div>